version: '3'

services:
  web:
    restart: always
    build: ./nginx/web
    image: 127.0.0.1:5000/web
    # expose:
    #   - "8000"
    ports: 
      - "8000:8000"

    # links:
    #   - postgres:postgres
    #   - redis:redis

    networks:
        - frontend
        - backend

    volumes:
      - /var/log:/log
      - /code/static
    env_file: .env
    environment:
      DEBUG: 'true'

    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    image: 127.0.0.1:5000/nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
      - /var/log:/log
      # - web:/

    networks:
        - frontend


# docker pull hub.c.163.com/public/redis:2.8.4

  postgres:
    restart: always
    image: hub.c.163.com/library/postgres:latest    
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

    networks:
        - backend

# docker pull hub.c.163.com/library/postgres:latest

  redis:
    restart: always
    image: hub.c.163.com/library/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
        - backend


networks:
    frontend:
    backend:


volumes:
    pgdata:
    redisdata:
