version: '3'

services:
  web:
    restart: always
    # build: ./web
    image: 127.0.0.1:5000/web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - /home/zw/dockerizing-django/web:/usr/src/app
      - /home/zw/dockerizing-django/log:/log
    env_file: .env
    environment:
      DEBUG: 'true'

    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    # build: ./nginx/
    image: 127.0.0.1:5000/nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
      - /home/zw/dockerizing-django/web/static:/static
      - /home/zw/dockerizing-django/log:/log

    # volumes_from:
    #   - web
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /redisdata:/data